config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "blog_posts#index"

  resources :blog_posts do
    resource :cover_image, only: :destroy, module: :blog_posts
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id           :bigint           not null, primary key
#  published_at :datetime
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class BlogPost < ApplicationRecord
  has_rich_text :content
  has_one_attached :cover_image
  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later

    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_params, only: %i(show edit update destroy)
  before_action :authenticate_user!, except: %i(index show)

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :cover_image, :published_at)
  end

  def set_params
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: blog_post do |form| %>
<% if form.object.errors.any? %>
  <div class="m-3">
    <% form.object.errors.full_messages.each do |error| %>
      <div><%= error %></div>
    <% end %>
  <div>
<% end %>
  <div class="flex flex-col m-3">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="flex flex-col m-3">
    <%= form.label :cover_image %>
    <% if blog_post.cover_image.present? %>
      <div id="<%= dom_id(blog_post, :cover_image) %>">
        <%= image_tag blog_post.cover_image, class: "w-1/3" %>
        <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you Sure ?" } %>
      </div>
    <% end -%>
      <%= form.file_field :cover_image %>
  </div>

  <div class="flex flex-col m-3">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="flex flex-col m-3">
    <%= form.label :published_at %>
    <div>
      <%= form.datetime_select :published_at, include_blank: true %>
    </div>
  </div>
  <%= form.button class:"bg-blue-500 hover:bg-blue-700 text-white font-bold m-3 py-2 px-4 rounded" %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>
<%= render 'form', blog_post: @blog_post %>
<%= link_to 'Delete', blog_post_path(@blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you Sure ?" } %>

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>
<%= link_to 'New Post', new_blog_post_path if user_signed_in? %>
<% @blog_posts.each do |post| %>
  <div>
    <h2><%= link_to post.title, post %></h2>
    <%= image_tag(post.cover_image, size: "200x200") if post.cover_image.present? %>
    <% if post.draft? %>
      <div class="bg-blue-400 p-2 text-white rounded">Draft</div>
    <% elsif post.scheduled? %>
      <div class="bg-gray-400 p-2 text-green-900 rounded">Scheduled</div>
    <% end %>
  </div>
    Created at <%= link_to post.created_at.strftime("%d %b %Y at %H:%M") %>
    <br>
    <% if post.published_at.present? %>
    Published At     <%= link_to post.published_at.strftime("%d %b %Y at %H:%M") %>
    <% end -%>
  <% end -%>

<% if @pagy.pages > 1 %>
<div class="my-16">
<%== pagy_nav(@pagy) %>
</div>
<% end -%>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<% if user_signed_in? %>
<%= render 'form', blog_post: @blog_post %>
<% end %>

app/views/blog_posts/show.html.erb
<%= link_to "Back to Root", blog_posts_path %>
<% if @blog_post.present? %>
<h1><%= @blog_post.title %></h1>
<%= image_tag @blog_post.cover_image if @blog_post.cover_image.present? %>
<%= @blog_post.content %>
<%= @blog_post.published_at.strftime('%b %e %Y') if @blog_post.published_at.present? %>
<div>
<%= link_to 'Edit', edit_blog_post_path(@blog_post) if user_signed_in? %>
</div>
<% end%>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogGo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto my-16">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>